### ISSUE TITLE
直接输入链接search_url似乎不能运行，只能通过keyword, location_id，channel_id这种方式

### ISSUE THREAD

**Issue by wenhanweime** [Sniper970119/dianping_spider#8]
rt, config里说填写search_url会默认以上参数无效，这个功能似乎并没有实现

Traceback (most recent call last):
  File "/home/geolab/anaconda3/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/home/geolab/anaconda3/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/geolab/anaconda3/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'keyword'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 27, in <module>
    keyword = global_config.getRaw('detail', 'keyword')
  File "/home/geolab/dianping_spider/utils/config.py", line 42, in getRaw
    return self._configRaw.get(section, name)
  File "/home/geolab/anaconda3/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'keyword' in section: 'detail'

**Comment by Sniper970119** [comment]
无效不代表可以删

**Comment by wenhanweime** [comment]
> 无效不代表可以删

感谢回复，已成功实现
